apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-certificate
  namespace: test-ecommerce
spec:
  secretName: app-certificate
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  commonName: app.hextech.online
  dnsNames:
  - app.hextech.online