apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-ecommerce
  namespace: test-ecommerce
spec:
  interval: 1m0s
  url: https://github.com/TlStephen2011/test-ecommerce.git
  secretRef:
    name: test-ecommerce-deploy-key
  ref:
    branch: main