apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-certificate
  namespace: test-ecommerce
spec:
  secretName: api-certificate
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  commonName: ecommerce.hextech.online
  dnsNames:
  - ecommerce.hextech.online